version: '3.5'
services:
  asl-tf-serving:
    build:
      context: .
      dockerfile: ./Dockerfile-tf-serving-prd
    image: tf-production
    container_name: asl-tf-serving
    restart: always
    environment:
      - MODEL_NAME=asl_classifier_model
    ports:
      - 8501:8501
      - 8500:8500
networks:
  default:
    name: web_dev
