version: '3.5'
services:
  asl-tf-serving:
    image: tensorflow/serving
    container_name: asl-tf-serving
    restart: always
    environment:
      - MODEL_NAME=asl_classifier_model
    volumes:
      - ./asl_classifier_model:/models/asl_classifier_model
    ports:
      - 8501:8501
      - 8500:8500
networks:
  default:
    name: web_dev
