#build react
FROM node:10-alpine as react-build
WORKDIR .
COPY . ./
RUN yarn install
RUN touch /frontend/.env.production
RUN echo 'REACT_APP_DOMAIN=http://localhost:5000' >> /frontend/.env.production
RUN yarn build
#not needed for smoke tests hence disable
FROM nginx:alpine
COPY --from=react-build /frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]