FROM python:3.6.3

# set working directory
RUN mkdir -p /usr/src/ASL-detector

COPY . /ASL-detector
WORKDIR /ASL-detector/asl-api
# add requirements
#ADD ./asl-api/requirements.txt /usr/src/app/requirements.txt

ENV AM_I_IN_A_DOCKER_CONTAINER = yes
# install requirements
RUN pip install -r requirements.txt




# run worker
ENTRYPOINT celery -A celeryTask.app  worker --loglevel=debug
