apiVersion: apps/v1
kind: Deployment
metadata:
  name: asl-application
spec:
  replicas: 2
  selector:
    matchLabels:
      run: asl-application
  template:
    metadata:
      labels:
        run: asl-application
    spec:
      containers:
        - name: asl-api
          image: gcr.io/cs161-prd/asl-api-dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
        - name: asl-ui
          image: gcr.io/cs161-prd/asl-ui-prd:latest
          imagePullPolicy: Always
          env:
            - name: REACT_APP_DOMAIN
              value: 'http://35.222.107.130:5000/'
          ports:
            - containerPort: 80
              protocol: TCP
        - name: asl-worker
          image: gcr.io/cs161-prd/asl-worker:latest
          imagePullPolicy: Always
        - name: asl-tf-serving
          image: gcr.io/cs161-prd/asl-tf-serving:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8500
              protocol: TCP
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
              protocol: TCP
        - name: redis
          image: redis:3.0-alpine
          ports:
            - containerPort: 6379
              protocol: TCP
