apiVersion: v1
kind: Service
metadata:
  name: ASL-Application-LoadBalancer
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 5000
      targetPort: 5000
