// flow-typed signature: b3e58900c9f2ed396cbfaac60cd206ab
// flow-typed version: <<STUB>>/@vikr01/eslint-config_v^0.0.0-rc.2/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vikr01/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vikr01/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vikr01/eslint-config/dist/flowtype' {
  declare module.exports: any;
}

declare module '@vikr01/eslint-config/dist/import' {
  declare module.exports: any;
}

declare module '@vikr01/eslint-config/dist/index' {
  declare module.exports: any;
}

declare module '@vikr01/eslint-config/dist/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vikr01/eslint-config/dist/flowtype.js' {
  declare module.exports: $Exports<'@vikr01/eslint-config/dist/flowtype'>;
}
declare module '@vikr01/eslint-config/dist/import.js' {
  declare module.exports: $Exports<'@vikr01/eslint-config/dist/import'>;
}
declare module '@vikr01/eslint-config/dist/index.js' {
  declare module.exports: $Exports<'@vikr01/eslint-config/dist/index'>;
}
declare module '@vikr01/eslint-config/dist/types.js' {
  declare module.exports: $Exports<'@vikr01/eslint-config/dist/types'>;
}
declare module '@vikr01/eslint-config/index' {
  declare module.exports: $Exports<'@vikr01/eslint-config'>;
}
declare module '@vikr01/eslint-config/index.js' {
  declare module.exports: $Exports<'@vikr01/eslint-config'>;
}
